Fixed examples
alexcg1/simple-jina-examples pull request #4
Opened 2021-12-08 09:23 UTC by joeyouss

2021-12-09 13:18 UTC, alexcg1 requested changes

2021-12-09 13:18 UTC, alexcg1 commented on README.md
> +This may be due to using an older version of hub. Please delete your cache using `rm -rf ~/.jina` and then try running again.
- `hub` -> `Jina Hub`

2021-12-09 13:18 UTC, alexcg1 commented on basics/2_executor_options/app.py
>          name="encoder",
you'll also need to add `install_requirements=True`

2021-12-09 13:18 UTC, alexcg1 commented on basics/2_executor_options/app.py
>          name="encoder",
Do this for each occurrence

2021-12-09 13:37 UTC, joeyouss commented
@alexcg1 changes made!

2021-12-09 13:59 UTC, alexcg1 reviewed
A few more changes. I shoulda caught them first time

2021-12-09 13:59 UTC, alexcg1 commented on README.md
> +This may be due to using an older version of Jina Hub. Please delete your cache using `rm -rf ~/.jina` and then try running again.
Actually I messed that up:
- `an older version of Jina Hub` -> `older versions of Hub Executors`

2021-12-09 13:59 UTC, alexcg1 commented on basics/3_document_generators/app.py
> +        install_requirements=True
Sorry, if we have `+docker` we don't need `install_requirements`

2021-12-09 13:59 UTC, alexcg1 commented on basics/3_document_generators/app.py
> +        install_requirements=True
So keep it for spacy, remove it for simpleindexer

2021-12-10 04:23 UTC, joeyouss commented
@alexcg1 please check

2021-12-10 11:29 UTC, alexcg1 approved these changes
LGTM :+1: You can go ahead and merge this!

2021-12-10 13:03 UTC, merged